PUBLIC CONVERT_ZERO
extrn CONVERT_LOOP:FAR
CONVERT SEGMENT
    ASSUME CS:CONVERT
CONVERT_ZERO PROC FAR
  ADD DL, '0'                  ; 将余数转换为ASCII字符
  MOV [DI], DL                 ; 存入buffer中
  DEC DI
  MOV [DI], DL
  DEC DI
  MOV AX, BX
  CMP AX, 0
  JZ END1 
  CALL CONVERT_LOOP
END1: 
  RET
CONVERT_ZERO ENDP
CONVERT ENDS
end

